### ISSUE TITLE
AP Mode Cannot Be Restarted After `cyw43_arch_disable_ap_mode`

### ISSUE THREAD

**Issue by eightycc** [georgerobotics/cyw43-driver#106]
CircuitPython attempts to restart AP mode (`cyw43_arch_enable_ap_mode`) subsequent to its having been previously started (`cyw43_arch_enable_ap_mode`) and stopped (`cyw43_arch_disable_ap_mode`). All subsequent attempts to restart `cyw43_tcpip_link_status` return `CYW43_LINK_DOWN`.

Tracing indicates that this is due to a race condition between `cyw43_wifi_setup` and asynchronous setting of `NETIF_FLAG_LINK_UP` by `netif_set_link_up` in LWIP.

On the first start of the AP, the CYW43439 takes longer to bring the link up and signal asynchronously than it does on subsequent attempts. For the first AP start `cyw43_wifi_setup()` is able to complete `CYW43_cb_tcpip_init()` before the CYW43439 signals that the link is up, so `NETIF_FLAG_LINK_UP` does not get clobbered. On subsequent starts of the AP, the CYW43439 signals that the link is up almost immediately so `CYW43_cb_tcpip_init()` clears `NETIF_FLAG_LINK_UP` after it has already been set.

See https://github.com/adafruit/circuitpython/issues/8718 for additional details.

**Comment by dpgeorge** [comment]
Fixed by 089a75340e88f6a6d4787e50f9439940af80e11f
