### ISSUE TITLE
Firmware loading seems to cause USB problems for macs

### ISSUE THREAD

**Issue by peterharperuk** [georgerobotics/cyw43-driver#11]
See https://github.com/micropython/micropython/issues/8904

We've tested a fix that adds strategic calls to MICROPY_EVENT_POLL_HOOK at appropriate places and it seems to fix the issue. We have to put some hooks in the driver.

**Comment by dpgeorge** [comment]
Addressed by cd4075fc7d8c835431f5bed0e332f5a193990797
