### ISSUE TITLE
RFE: an API call to get the RSSI of just the currently connected AP

### ISSUE THREAD

**Issue by slimhazard** [georgerobotics/cyw43-driver#35]
Related to #34: I suggest a function in the API that returns the RSSI of the currently connected AP.

In #34 I described running `cyw43_wifi_scan()` (now working), which I was doing because it is apparently the only way to get any RSSI value. In fact I just want to find it out for the current AP, so I'm running the scan and getting the RSSI in the callback when the SSID matches, and ignoring every other result of the scan.

In [this forum thread](https://forums.raspberrypi.com/viewtopic.php?t=340680), a Raspberry Pi engineer stated that obtaining the RSSI for the current AP is supported, but not exposed by the driver. So I think it would be a sensible addition (and would avoid a lot of superfluous scanning).

**Comment by maxnet** [comment]
Sample code how to do this with cyw43_ioctl() here: https://forums.raspberrypi.com/viewtopic.php?p=2047463#p2047467
