### ISSUE TITLE
minor: configurable default interface params before dhcp is up

### ISSUE THREAD

**Issue by bruelltuete** [georgerobotics/cyw43-driver#41]
In `cyw43_cb_tcpip_init()`, there are some parameters configured for the interface before dhcp has had a chance to run.
Would be nice if those were configurable (via macros?).
Esp the google dns server probably warrants a more prominent entry in a config file, e.g. cyw43_configport.h.
https://github.com/georgerobotics/cyw43-driver/blob/2ab6ca93f9cd044bc6f35c1403b1284e4161294a/src/cyw43_lwip.c#L143

**Comment by peterharperuk** [comment]
Yes, you're right.

**Comment by dpgeorge** [comment]
Fixed by 5f396836c8e9a748849b121377bf442388571716
