### ISSUE TITLE
Can't disable LWIP_DHCP

### ISSUE THREAD

**Issue by peterharperuk** [georgerobotics/cyw43-driver#48]
See https://github.com/raspberrypi/pico-sdk/issues/1107

**Comment by peterharperuk** [comment]
You probably also need https://github.com/georgerobotics/cyw43-driver/issues/41 to specify your IP address if you disable DHCP?

**Comment by dpgeorge** [comment]
Fixed by 4be372ccf234e3ff4d790d92ec96b21ae1497ea8
