### ISSUE TITLE
It would be nice to be able to query the current wifi power management number

### ISSUE THREAD

**Issue by peterharperuk** [georgerobotics/cyw43-driver#5]
Currently you can run wlan.config(pm = 0xadbrrm) but you can't run wlan.config("pm")
I'm thinking that we might need to fiddle with the power management numbers (e.g. https://github.com/raspberrypi/pico-sdk/issues/912), so it would be useful to have a way to dump the current value being used.

**Comment by dpgeorge** [comment]
A call to `cyw43_read_iovar_u32(...)` will be able to retrieve these values.
