### ISSUE TITLE
Tag v1.0.2 is not annotated

### ISSUE THREAD

**Issue by oliver-joos** [georgerobotics/cyw43-driver#92]
We use a Python script that calls `git submodule status lib/cyw43-driver` to retrieve the version and commit number of this driver. This relies on _annotated tags_ and failed until I added a note to tag v1.0.2 on my fork of this repo.
Please consider to annotate tag v1.0.2 in your repo as well.

**Comment by dpgeorge** [comment]
Yes, annotating the tag is a good idea.  Previous tags have been annotated, and I forgot to do v1.0.2.

That's now fixed, and the tag has been force pushed to add the annotation.

To update a clone, use `git pull --tags --force`.

**Comment by oliver-joos** [comment]
Thank you, now our versioning works!

Meanwhile I added my own tag annotation on my fork.
To overwrite the tags on my remote "origin" with those on your "georgerobotics" I did:
```
git fetch --tags --force georgerobotics
git tag --list -n99   # to check local tags and annotations
git push --tags --force origin
```

**Comment by dpgeorge** [comment]
Great, thanks for confirming it works for you.
